CRITERION:
  NAME: ce
DATALOADER:
  BATCH_SIZE: 4
  NUM_WORKERS: 4
DATASET:
  NAME: lane
  NUM_CLASSES: 2
  ROOT: /home/zxj/Documents/star-ai-2022/lane
  TRANSFORM:
    ADAPTIVE_CROP:
      HEIGHTS: []
      LEFTS: []
      ORIGIN_HEIGHTS: []
      ORIGIN_WIDTHS: []
      TOPS: []
      WIDTHS: []
    NORMALIZE:
      MEAN:
      - 0.485
      - 0.456
      - 0.406
      STD:
      - 0.229
      - 0.224
      - 0.225
    RESIZE:
      HEIGHT: 2400
      WIDTH: 1080
EPOCHS: 10
ITERATIONS: 72910
MODEL:
  NAME: efficientnet-b0
OPTIMIZER:
  LR: 0.1
  MOMENTUM: 0.0
  NAME: sgd
  WEIGHT_DECAY: 0.0005
SCHEDULER:
  BY_EPOCH: true
  BY_ITERATION: false
  GAMMA: 0.5
  NAME: exp
