CRITERION:
  NAME: ce
DATALOADER:
  BATCH_SIZE: 8
  NUM_WORKERS: 8
DATASET:
  NAME: lane
  NUM_CLASSES: 2
  ROOT: /home/zxj/Documents/star-ai-2022/lane
  TRANSFORM:
    ADAPTIVE_CROP:
      HEIGHTS: []
      LEFTS: []
      ORIGIN_HEIGHTS: []
      ORIGIN_WIDTHS: []
      TOPS: []
      WIDTHS: []
    NORMALIZE:
      MEAN:
      - 0.485
      - 0.456
      - 0.406
      STD:
      - 0.229
      - 0.224
      - 0.225
    RESIZE:
      HEIGHT: 2400
      WIDTH: 1080
EPOCHS: 8
ITERATIONS: 29160
MODEL:
  NAME: resnet-18
OPTIMIZER:
  LR: 0.01
  MOMENTUM: 0.0
  NAME: sgd
  WEIGHT_DECAY: 0.0005
SCHEDULER:
  BY_EPOCH: true
  BY_ITERATION: false
  GAMMA: 0.9
  NAME: exp
